name: Release
on:
  push:
    tags:
      - '**'

jobs:
  dynamic:
    name: Build Dynamic
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build
        run: |
          set -e
          go build cmd/wtfd.go
          strip wtfd

      - name: Prepare artifact upload
        run: |
          set -e
          mkdir build
          cp -r icon.svg html/ wtfd build/

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: wtfd-dynamic
          path: build

  static:
    name: Build Static
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: |
          set -e
          sudo apt-get update && sudo apt-get -y install musl-tools

      - name: Build (with musl)
        env:
          CC: musl-gcc
        run: |
          set -e
          go build -ldflags '-linkmode external -extldflags "-static"' -v cmd/wtfd.go
          strip wtfd

      - name: Prepare artifact upload
        run: |
          set -e
          mkdir build
          cp -r wtfd icon.svg html build/

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: wtfd-static
          path: build

  test:
    name: Run Test
    runs-on: ubuntu-latest
    needs: [dynamic, static]
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Install Dependencies
        run: |
          set -e
          sudo apt-get update && sudo apt-get install -y zip
      - name: Download Dynamic
        uses: actions/download-artifact@master
        with:
          name: wtfd-dynamic
          path: dynamic
      - name: Download Static
        uses: actions/download-artifact@master
        with:
          name: wtfd-static
          path: static
      - name: Zip
        run: |
          set -e
          zip -r wtfd-static.zip static/.
          zip -r wtfd-dynamic.zip dynamic/.
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: |
            wtfd-static.zip
            wtfd-dynamic.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
